language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
    - SUITE=centos
    - SUITE=ubuntu
    - SUITE=debian

sudo: true
dist: trusty
bundler_args: --with=docker --without vagrant windows

before_install:
  - pip install --user -r test-requirements.txt

script:
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 4
  # Provision containers
  - bundle exec kitchen converge $SUITE
  # Run test-kitchen with docker driver:
  - bundle exec kitchen verify $SUITE

after_script:
  - bundle exec kitchen list $SUITE
  - bundle exec kitchen destroy $SUITE
