language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - subversion
    - git
    - shellcheck
    - tree

rvm:
  - 2.2.4
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: true

bundler_args: --without='vagrant'

install:
  # DEPRECATED
  # init/start docker in travis
  #- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)
  #
  # clone & setup ci for test formula
  - export FORMULA=salt-formula-git
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --without='vagrant'
  - git clone https://github.com/salt-formulas/$FORMULA.git --branch master --single-branch ../$FORMULA
  - cd ../$FORMULA
  - cp -R ../kitchen-salt/spec/fixtures/formula-foo .
  - for f in Rakefile .kitchen.salt.yml; do test -e $f || cp ../kitchen-salt/$f . ;done
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen list

script:
  # Run unit tests
  - cd $TRAVIS_BUILD_DIR && bundle exec rspec
  # Check shell scripts
  - shellcheck lib/kitchen/provisioner/*.sh*
  # Run test-kitchen with docker driver:
  - cd ../$FORMULA && KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen test client-single-ubuntu-1404 -ldebug

after_failure:
  - cat .kitchen/logs/client-single-ubuntu-1404.log

after_script:
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen list
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen destroy all
  - KITCHEN_LOCAL_YAML=.kitchen.salt.yml bundle exec kitchen diagnose --all
